version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  artists:
    build:
      context: ./artists
    ports:
      - 5000:5000
    volumes:
      - ./artists:/app