version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  api:
    build:
      context: ./backend/api
    ports:
      - 5000:5000
    volumes:
      - ./backend/api:/app