# Enter poetry shell
shell:
  poetry shell

# Run pytest suite
test: shell
  poetry run pytest

# Run the application on the local machine
run: shell
  poetry run python main.py

# Build the docker image
build:
  docker build -t ddicks98/pclr:latest .

# Run the `pclr` docker image
run-docker: build
  docker run pclr:latest

# Cross build to linux/amd64 platform
build-amd:
  docker build --platform linux/amd64 -t ddicks98/pclr:latest .
