service: play-counter

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  environment:
    REGION_NAME: us-east-1
    SPOTIFY_TABLES: spotify_track_count, spotify_cache
    SPOTIFY_TRACKS_TABLE: spotify_track_count
    SPOTIFY_CACHE_TABLE: spotify_cache
    API_SCOPES: user-read-recently-played
    CLIENT_ID_KEY: spotify_client_id
    CLIENT_SECRET_KEY: spotify_secret
    SPOTIFY_SECRETS: arn:aws:secretsmanager:us-east-1:357317004725:secret:Spotify_Client_Secrets-qPW7mA
    EVENT_BRIDGE_RULE: play-counter-dev-PlayDashcounterEventsRuleSchedule-DRBP6IDXXM02

package:
  exclude:
    - .pytest_cache/**
    - venv/**
    - tests/**
    - node_modules/**
    - package*.json
    - .vscode/**

functions:
  play-counter:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
