# Enter poetry shell
shell:
  poetry shell

# Run pytest suite
test: shell
  poetry run pytest

# Run the application on the local machine
run: shell
  poetry run python main.py

# Build the docker image
dbuild:
  docker build -t pclr -f Dockerfile .

# Run the `pclr` docker image
drun: dbuild
  docker run pclr:latest
