version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    restart: always
    ports:
      - 8000:8000
    environment:
      - CONNECTIONSTRING=mongodb://mongo:27017/datafy
    volumes:
      - .:/app

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb: null
  mongodb_config: null
