name: Build Backend API Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-api:
    name: Build API Server Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build -t datafy-api:$(date +%s) .
        working-directory: api/
