name: Docker Image Workflow

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-api:
    name: Build Core API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag datafy-api:$(date +%s) --target dev
        working-directory: backend/api
