name: Build Backend API Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-api:
    name: Build Backend API Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag datafy-api:$(date +%s) --target runtime
        working-directory: api/
