name: Test Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api-server:
    name: Test Backend API Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install Poetry
        run: python -m pip install -U pip poetry
        working-directory: api/

      - name: Install Release Dependencies
        run: poetry install
        working-directory: api/

      - name: Run API Test Suite
        run: poetry run pytest
        working-directory: api/
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

  test-cli:
    name: Rust CLI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run Test Suite
        run: cargo test
        working-directory: cli
