name: Test Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend-api-service:
    name: Test Backend API Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install Poetry
        run: python -m pip install -U pip poetry
        working-directory: backend/fapi

      - name: Install Release Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install
        working-directory: backend/fapi

      - name: Run Test Suite
        run: poetry run pytest
        working-directory: backend/fapi
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

  test-cli:
    name: Rust CLI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run Test Suite
        run: cargo test
        working-directory: cli
