name: Test Python Packages

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Backend API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install poetry
        run: python -m pip install -U pip poetry git+git://github.com/samuelcolvin/pydantic@master#egg=pydantic
        working-directory: backend/api

      - name: Install Dependencies
        run: poetry install
        working-directory: backend/api

      - name: Setup Access Token
        run: echo ${{ secrets.ACCESS_TOKEN }} >> .cache
        working-directory: backend/api

      - name: Run Test Suite
        run: poetry run pytest
        working-directory: backend/api
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
